### ISSUE TITLE
MLU app throws error if you restrict age range to a single year (pr)

### ISSUE THREAD

**Issue by kemacdonald** [langcog/childes-db-shiny#7]
<img width="975" alt="screen shot 2017-10-03 at 8 50 30 am" src="https://user-images.githubusercontent.com/6145443/31140780-5523121e-a82a-11e7-9da1-b291214a57e3.png">

**Comment by kemacdonald** [comment]
Same thing for the Frequency Counts app

**Comment by amsan7** [comment]
ok yeah this was cause there was no data for exact ages and `facet_wrap` freaked out
