### ISSUE TITLE
Frequency Counts app throws error when you add more than one word (pr)

### ISSUE THREAD

**Issue by kemacdonald** [langcog/childes-db-shiny#8]
Not sure if I'm using the interface correctly, but this is one of the first things I tried: 

<img width="1021" alt="screen shot 2017-10-03 at 11 14 17 am" src="https://user-images.githubusercontent.com/6145443/31141370-17e659a4-a82c-11e7-872c-8aa673ed7b79.png">

**Comment by amsan7** [comment]
this one's related to other issue in that empty data will break `facet_wrap`. so the word "shoe, dog" is not found. it's fixed, but now a little concerned about whether we should add support for multiple words / is it obvious that you can only enter 1 word

@mcfrank any reason we used `textInput` for word and not `selectizeInput`? Too many tokens?

**Comment by smeylan** [comment]
Looks like there is still a problem here: the date picker changes to NaN- NaN when a second word is added
<img width="1132" alt="screen shot 2017-11-02 at 9 23 31 am" src="https://user-images.githubusercontent.com/779916/32328241-bcb0f152-bfaf-11e7-82ae-45c39543fc85.png">

**Comment by amsan7** [comment]
It happens when any word not in the DB is entered - but yeah it's not great to show empty plot and NaNs. Probably a better way to convey that word isn't found / we should add support for multiple words
